# 默认环境变量
APP_TITLE: Ciel实验室
PRJ_ENV: production

APP_ID: ""

# 接口配置
HOST: https://nadokaciel.cn
AUTH_LOGIN_API: /wechat/miniapp/v1/auth
API_APP_KEY: ""
API_APP_CODE: ""

# 接口配置
ALIAPP_AUTH_LOGIN_API: /alipay/miniapp/v1/auth
ALIAPP_API_APP_KEY: ""
ALIAPP_API_APP_CODE: ""

# 重试错误码
TOKEN_ERROR_CODE: [40003, 40004, 40005]